name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 'lts/*'
        - name: Install
          run: npm install 

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 'lts/*'
        - name: Test
          run: npm test 